<?php

/**
 * Created by PhpStorm.
 * User: Kanat
 * Date: 23.07.2017
 * Time: 16:17
 */

namespace app\modules\admin;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


class Module extends \yii\base\Module
{
    public $controllerNamespace = 'app\modules\admin\controllers';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


}